/*
 * This source file was generated by the Gradle 'init' task
 */
package taller3;

public class App {

   public static void main(String[] args) {

      System.out.println(Escribir_asc(4, 3, 2));
      System.out.println(Obtener_cifras(10));
      System.out.println(Clasificar_char('a'));
      System.out.println(Hallar_division_exacta(10, 5));
      System.out.println(Consultar_hab((byte)2, "AA"));
      System.out.println(Obtener_obs(true, false, false));
      System.out.println(Conocer_invitacion("verde"));

   }

   /*
    * 1. Construya un algoritmo e implemente la función en Java Escribir_asc que
    * reciba tres números enteros diferentes
    * y devuelva en un String en orden ascendente con el siguiente formato:
    * "##### - ##### - #####", donde el primero es
    * el mayor de todos, el segundo el del medio, el tercero el menor de todos. Si
    * hay al menos dos números iguales,
    * devolverá el mensaje: "Error: La función no considera números iguales". Si
    * hay un error inesperado, deberá mostrar
    * el mensaje: "Ocurrió un error inesperado".
    */

    public static String Escribir_asc(int n1, int n2, int n3){

      try {

         if (n1 > n2 && n1 > n3 && n2 < n1 && n2 > n3) {
            return n1 + " - " + n2 + " - " + n3;         
         }
         else if (n1 > n2 && n1 > n3 && n3 < n1 && n3 > n2) {
            return n1 + " - " + n3 + " - " + n2; 
         }
         if (n2 > n1 && n2 > n3 && n1 < n2 && n1 > n3) {
            return n2 + " - " + n1 + " - " + n3;         
         }
         else if (n2 > n1 && n2 > n3 && n3 < n2 && n3 > n1) {
            return n2 + " - " + n3 + " - " + n1; 
         }
         if (n3 > n1 && n3 > n2 && n2 < n3 && n2 > n1) {
            return n3 + " - " + n2 + " - " + n1;         
         }
         else if (n3 > n1 && n3 > n2 && n1 < n3 && n1 > n2) {
            return n3 + " - " + n1 + " - " + n2; 
         }
         else 
            return "Error: La función no considera números iguales";
      } 
      catch (Exception e) {
         return "Ocurrió un error inesperado";
      }
    }

   /*
    * 2. Construya un algoritmo e implemente la función en Java Obtener_cifras que
    * recibe un número entre 0 y 50.000
    * y devuelve byte con las cifras que tiene. Por ejemplo 10 tiene dos cifras,
    * 9999 tiene 4 cifras. Si el número
    * no está en el rango devuelve 0. Y si hay un error inesperado, devuelve -1.
    * 
    */

   public static byte Obtener_cifras(int n){

      try {
         final byte r1 = 0, r2 = 1, r3 = 2, r4 = 3, r5 = 4, r6 = 5;
         final int max = 50000, min = 0, min2 = 10, min3 = 100, min4 = 1000, min5 = 10000;

         if (n < min && n > max)
            return r1;

         if (n >= min && n < min2){
            return r2;
         }
         else if (n >= min2 && n < min3){
            return r3;
         }
         else if (n >= min3 && n < min4){
            return r4;
         }  
         else if (n >= min4 && n < min5){
            return r5;
         }
         else if (n >= min5 && n <= max){
            return r6;
         }
         else
            return 0;
      } 
      catch (Exception e) {
         return -1;
      }
   }

   /*
    * 3. Construya un algoritmo e implemente la función en Java Clasificar_char que
    * recibe un caracter, y
    * devuelve un string de acuerdo con las siguientes condiciones: si es un
    * alfabético, deuvelve "ES LETRA";
    * si es numérico, devuelve "ES NUMERO" o si es un carácter especial, devuelve
    * "ESPECIAL".
    * Los caracteres se validan de acuerdo con la tabla ascii básica y lo explicado
    * en clase.
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */

   public static String Clasificar_char(char caracter){

      try {
         if (caracter <= 'z' && caracter >= 'a' || caracter <= 'Z' && caracter >= 'A'){
            return "ES LETRA";
         }
         else if (caracter <= '9' && caracter >= '0'){
            return "ES NUMERO";
         }
         else if (caracter <= 47 && caracter >= 33 || caracter <= 64 && caracter >= 58 || caracter <= 96 && caracter >= 91 || caracter >= 123 && caracter <= 254){
            return "ESPECIAL";
         }
         else {
            return "Ocurrió un error inesperado";
         }
      } 
      catch (Exception e) {
         return "Ocurrió un error inesperado";
      }
   }

   /*
    * 
    * 4. Construya un algoritmo e implemente la función en Java
    * Hallar_division_exacta que pida dos números enteros,
    * calcule la división del primero sobre el segundo, y al final si la división
    * es exacta, devuelva "DIVISION EXACTA"
    * y de lo contrario devuelva "DIVISION NO EXACTA". (Exacta significa que tiene
    * cociente, pero no residuo).
    * 
    * Si alguno de los dos números que recibe es cero o negativo, devuelva
    * "NO SE ADMITE CERO O NEGATIVOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * Nota: Revise el funcionamiento del operador mod que le puede ayudar.
    * 
    * 
    * 
    */

   public static String Hallar_division_exacta(int n1, int n2){

      byte min = 0;
      if (n1 <= min|| n2 <= min)
         return "NO SE ADMITE CERO O NEGATIVOS";

      try {

         if (n1%n2==min){
            return "DIVISION EXACTA";
         }
         else
            return "DIVISION NO EXACTA";
      }
      catch (Exception e) {
         return "Ocurrió un error inesperado";
      }
   }

   /*
    * 5. En la siguiente tabla se encuentra la información de las habitaciones de
    * una finca hotel:
    * 
    * Habitación Camas Planta    AA/VENTILADOR
    *    101         2     Primera     AA
    *    102         1     Primera     VE
    *    201         3     Segunda     AA
    *    202         2     Segunda     VE
    *    301         2     Tercera     AA
    * 
    * 
    * Construya un algoritmo e implemente la función en Java Consultar_hab que
    * reciba en un byte el número de camas
    * y en un string si desea VE o AA, y deuvelva en un texto el o los números de
    * habitación que cumplen ese requisito.
    * Si son varias habitaciones, devuelvalas separadas por el caracter |
    * (normalmente, al lado izquierdo de la tecla del 1).
    * Ejemplo: "101|301"
    * Si el número de camas no está entre 1 y 3 o el string es diferente a AA o VE,
    * devuelva "DATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */

   public static String Consultar_hab(byte nro_camas, String AA_VE){

      byte min_c = 1, med_c = 2, max_c = 3;
      if (nro_camas < min_c && nro_camas > max_c || AA_VE != "AA" && AA_VE != "VE")
         return "DATOS NO VÁLIDOS";

      try {

         if (nro_camas == min_c && AA_VE == "VE" ){
            return "102";
         }
         else if (nro_camas == med_c && AA_VE == "AA" ){
            return "101|301";
         }
         else if (nro_camas == med_c && AA_VE == "VE" ){
            return "202";
         }
         else if (nro_camas == max_c && AA_VE == "AA" ){
            return "201";
         }
         else 
            return "Ocurrió un error inesperado";

      } 
      catch (Exception e) {
         return "Ocurrió un error inesperado";
      }
   }

   /*
    * 
    * 6. Un restaurante vende 3 platos. Si el cliente solicita el plato 1, le dan
    * el postre gratis; si selecciona los platos
    * 1 y 2, le dan la bebida gratis y si selecciona los platos 1,2 y 3, le dan
    * postre y bebida.
    * Construya un algoritmo e implemente la función Obtener_obs en Java que reciba
    * 3 booleanos, uno para cada plato y en
    * un String devuelva el obsequio ganado en mayúscula, así: "BEBIDA", "POSTRE",
    * "BEBIDA Y POSTRE".
    * Si los 3 platos vienen en false, , devuelva "PLATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */

   public static String Obtener_obs(boolean p1, boolean p2, boolean p3){

      try {

         if (p1 == true && p2 == false && p3 == false){
            return "POSTRE";
         }
         else if (p1 == true && p2 == true && p3 == false){
            return "BEBIDA";
         }
         else if (p1 == true && p2 == true && p3 == true){
            return "BEBIDA Y POSTRE";
         }
         else 
            return "PLATOS NO VÁLIDOS";
         
      } 
      catch (Exception e) {
         return "Ocurrió un error inesperado";
      }
   }

   /*
    * 7. Un grupo de amigos hace un sorteo semanalmente con pelotas de ping pong,
    * para saber quién invita y a qué la próxima salida.
    * Las opciones dependen del color que sacan en cada bola y son:
    * 
    * verde: Invita a las cervezas
    * azul: Invita a la pizza
    * rojo: Invita al postre
    * amarillo: Paga el parqueadero de todos
    * blanco o negro: Vaya y disfrute
    * Si la función recibe algo diferente a los colores dados, debe retornar
    * "Error en el color".
    * 
    * Se necesita una función en java Conocer_invitacion que reciba un string con
    * el color de la bola y retorna un
    * String con exactamente el texto de la invitación correspondiente.
    * 
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */

   public static String Conocer_invitacion(String color_bola){

      try {

         if (color_bola == "verde"){
            return "Invita a las cervezas";
         }
         else if (color_bola == "azul"){
            return "Invita a la pizza";
         }
         else if (color_bola == "rojo"){
            return "Invita al postre";
         }
         else if (color_bola == "amarillo"){
            return "Paga el parqueadero de todos";
         }
         else if (color_bola == "blanco" || color_bola == "negro"){
            return "Vaya y disfrute";
         }
         else 
            return "Error en el color";
      } 
      catch (Exception e) {
         return "Ocurrió un error inesperado";
      }
   }
}
